### ISSUE TITLE
Enable different `output` and `src` value

### ISSUE THREAD

**Issue by crutchcorn** [xiphux/rehype-svimg#10]
I'm trying to use this library with https://astro.build, but to do this, I'd like to output the `generateImages` to `public` without `public` being prefixed to the `src` of the images.

**Comment by xiphux** [comment]
I'm not really familiar with Astro - can you provide more details on what your image directory structure looks like and what options you're passing into rehypeSvimg?

**Comment by acheronfail** [comment]
I have a similar requirement, I'm using [svelte kit](https://kit.svelte.dev/).

This provides a directory structure of:

```
src/      <-- source files
static/   <-- static assets bundled in and served at base url, ie: http://localhost/<HERE>
```

I'm using `rehype-svimg` with these options:

```js
.use(rehypeSvimg, {
	  inputDir: 'static',      // original images stored here
	  outputDir: `static/i`, // processed images stored here
	  webp: true,
	  avif: true,
	  generateImages: true,
  })
```

The problem happens that the `src` attribute of the images includes the `static` prefix, but my framework (svelte-kit) will strip the `static` from every item in static when building the site.

---

Perhaps we could have a hook or something to be able to change/update the `src` attribute somehow? Or tell `rehype-svimg` not to use the `outputDir` as a prefix, and provide another option as a prefix?

**Comment by crutchcorn** [comment]
Right, as @acheronfail was saying. My file directory is:

```
- content
    - posts
         - my-blog-post-slug
              - images.png
- public
```

Where I want the code to look like:

```
.use(rehypeSvimg, {
	  inputDir: 'content/posts/my-blog-post-slug',
	  outputDir: `public`,
	  webp: true,
	  avif: true,
	  generateImages: true,
  })
```

And the generated `img` and `srcset`s to be:

```
<img src="images.png"/>
```

Without:

```
content/posts/my-blog-post-slug
```

Or:

```
public
```

Prefixing the `src` path.

My current workaround is to use a second custom rehype parser to remove the prefix from the folder path:

https://github.com/unicorn-utterances/astro-unicorn-blog-starter/blob/16ad7fe2f4403f6a0b09e7a3e32cd5f1394b283b/src/utils/markdown/markdownToHtml.ts#L103-L123

But this is far from ideal.

**Comment by xiphux** [comment]
Ok. There are a couple existing options that do some amount of src rewriting, but I'm not sure that either of them are exactly what you're looking for.

For my site (which I originally built this for) I had created the [srcPrefix](https://github.com/xiphux/rehype-svimg#src-prefix) option (the examples given in that documentation are basically lifted exactly from my own site's structure). That's sort of what you're doing with inputDir, but the difference is that
* You want your output dir to live completely outside of your input dir, and
* You want your img urls to be relative and not absolute

svimg sort of makes some assumptions today about the relationship between inputDir and outputDir, in that it works best when outputDir lives inside inputDir (under the assumption that your static content lives within some sort of static asset directory both before and after the processing, and that your existing Image src already references files from that static asset directory). So it does some stripping of the resultant img src if (and only if) it detects that. So in the example with an inputDir of `static` and an outputDir of `static/i` and an `<Image src="content/posts/my-blog-post-slug/image.png" />` and the file living at `static/content/posts/my-blog-post-slug/image.png`, it could figure out that `static/i` was a subdirectory of `static` and rewrite the resultant src to be `i/content/posts/my-blog-post-slug/image.png`. That logic worked well with the way Sapper worked, but it won't work for you because of your totally separate input/output dirs.

There was a later [`publicPath` option](https://github.com/xiphux/svimg#preprocessor-options) added to svimg to override that logic and manually specify where the files live, that hasn't yet been exposed in rehype-svimg. That option was originally added for SvelteKit and compatibility with the way it handles nested routes (but also allowed other use cases such as CDNs). I'm not sure that just exposing that option would solve the problem for Astro, though, since you want your image src to be completely relative without any directory components. The `publicPath` option could specify where the src should live, but it can't really 'take away' parts of the src.

I'm guessing that the most flexible way to do this would be some sort of callback to transform the src as you mention. I'll need to think through how this interacts with the inputDir/outputDir options, and also work through what that means for existing publicPath and srcPrefix options, because it would be confusing to have multiple ways to do the same thing and this new option would likely deprecate one or both of those options.
